# Generated by Django 4.1.7 on 2023-03-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attemp',
        ),
    ]
