# Generated by Django 4.1.7 on 2023-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitstatus', models.CharField(max_length=200)),
                ('corr_ans', models.CharField(max_length=100)),
                ('persentage', models.CharField(max_length=100)),
                ('attm', models.CharField(max_length=100)),
                ('totq', models.CharField(max_length=100)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
