# Generated by Django 4.1.7 on 2023-03-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
