# Generated by Django 4.1.7 on 2023-03-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_attemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queno', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=100)),
                ('marking', models.BooleanField()),
                ('queattempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
