# Generated by Django 4.1.7 on 2023-03-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_attemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qno',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
